# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58866a0f0e25ed2599c4ffc1d91ca68c5849ce32495822c41feb95fed15b11ab3bee4379312c3df8ba882fba73e9c9725111b843d0cb3eb353d369f23f820be0

test:
  secret_key_base: 4b9e2bd785bf2b3f9d7c6fe089372e77975844e86ee39b0b8e1a1e0180491212a06def434e4e6ea552cb894e194bed5e3842096f1f1a7427b2cbfc364d1e1a5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
